name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Flutter using the stable channel and x64 architecture
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Step 3: Fetch Flutter dependencies
      - run: flutter pub get

      # Step 4: Navigate to iOS directory and install CocoaPods dependencies
      - run: pod repo update
        working-directory: ios

      # Install iOS Pod dependencies
      - run: pod install --verbose
        working-directory: ios

      # Step 5: Build the iOS release
      - run: flutter build ios --release --no-codesign

      # Step 6: Prepare IPA for release
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      # Step 7: Move the app into the Payload directory
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Step 8: Zip the Payload directory into an IPA file
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Step 9: Upload the IPA to GitHub Releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.5
          overwrite: true
          body: "Now the app using AI models for Classification & Background Removal"